### ISSUE TITLE
CLI require a graphical toolkit and an X server

### ISSUE THREAD

**Issue by GuillaumeRoques** [EasyinnovaSL/DPFManager#154]
Hi

I've got an error when trying to launch DPFManager on servers without graphical output (no screen plugged), tested on CentOS 6 and CentOS 7 with DPFManager 1.4 from http://www.preforma-project.eu/downloads/DPFManager/Release-1.4/Fedora/exec13-2016-01-29.zip.
This is the ouput from the terminal :
```
/opt/DPFManager/DPFManager -help
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:221)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:198)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:209)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:695)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$156(LauncherImpl.java:182)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
        ... 1 more
DPFManager Error invoking method.
DPFManager Failed to launch JVM
```

After some diggings on google I've installed the gtk2 graphical toolkit and after that the error is this one :
```
/opt/DPFManager/DPFManager -help
DPFManager Error invoking method.
DPFManager Failed to launch JVM
```

After some more diggings on google and java debug activation I've installed an X server (Xvfb fyi) and it works (with some warnings) :
```
/opt/DPFManager/DPFManager -help
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
Prism-ES2 Error : GL_VERSION (major.minor) = 1.4
Xlib:  extension "RANDR" missing on display ":1".
Usage: dpfmanager [options] source1 [source2 ... sourceN]
(the sources can be single TIF files, directories, zip files or URLs)
Options:
    -help: Displays this help message
    -v: Shows application version number
    -gui: Launches graphical user interface
    -configuration <filename>: Selects a configuration file
    -r[deepness]: Check directories recursively, with the specified depth. Default is '-r1'
    -s: Silent execution (do not open the report at the end)
```

**Comment by victormunoz** [comment]
Thanks for your comment.
We didn't run tests in terminals without graphical output.

We will try to find a better solution for that, so that the user doesn't need to do anything in such case.

After some investigation, it seems that disabling the hardware acceleration in the installer could solve the problem, but we need to verify it. I will keep this issue opened until we have a final answer.

**Comment by GuillaumeRoques** [comment]
Ok, thanks for your reply

**Comment by victormunoz** [comment]
This issue has been solved in the latest version (available in the development branch).
Also, we have created specific travis tests for non-gui systems to assure this, see: https://travis-ci.org/EasyinnovaSL/DPFManager/builds/123024720

**Comment by GuillaumeRoques** [comment]
Thanks!
