### ISSUE TITLE
Debian: cannot launch dpf-manager 3.0

### ISSUE THREAD

**Issue by tribouille** [EasyinnovaSL/DPFManager#309]
Hi,

I tried to install DPF using the .deb file.
Install seems to work.
But when I launch dpf-manager, it gives me some errors.
> DPFManager Failed to locate JNI_CreateJavaVM
> DPFManager Failed to launch JVM

It was working fine with the last version (2.6).

```sh
$wget http://www.blueroominnovation.com/dpfmanager/Downloads/Current-release/Debian/dpf-manager-3.0.deb -O /tmp/dpf-manager-3.0.deb
[...]
$sudo dpkg -i /tmp/dpf-manager-3.0.deb                           
Selecting previously unselected package dpf-manager.
(Reading database ... 345507 files and directories currently installed.)
Preparing to unpack /tmp/dpf-manager-3.0.deb ...
Unpacking dpf-manager (3.0) ...
Setting up dpf-manager (3.0) ...
$dpf-manager 
DPFManager Failed to locate JNI_CreateJavaVM
DPFManager Failed to launch JVM
```

Any ideas?

**Comment by tribouille** [comment]
I just tried on Fedora, I got the same problem.
(Using the package Fedora .rpm)

**Comment by victormunoz** [comment]
In version 3, the Java runtime has been removed from the application bundle...
The required version is **Java 8** which needs to be installed in the system in order to run the DPF Manager.
You can download it from here: https://www.java.com/es/download/

**Comment by JeromeMartinez** [comment]
We try to have no proprietary code on open source operating systems, the link you provide is for Oracle Java which is not open source, can't we use anymore OpenJDK (open source and available in the Linux distributions by default without having to rely on another external website) as with the previous version?

**Comment by victormunoz** [comment]
Yes. You can also use OpenJDK.
However, it does not include the JavaFX by default, so you will need to use the version of OpenJDK that includes JavaFX: https://wiki.openjdk.java.net/display/OpenJFX/Building+OpenJFX

This is the reason why we recommended to use the Oracle JDK, because it is much more easy to install (includes JavaFX by default).

**Comment by tribouille** [comment]
It seems Debian has the openjjx available: https://packages.debian.org/search?keywords=openjfx
I tried but got the same error.

I, then, tried with the Oracle one (x64 and x86), added the bin directory to my PATH, and got the same error.

OpenJDK:
```sh
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)
```

Oracle:
```sh
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) Server VM (build 25.111-b14, mixed mode)
```

**Comment by victormunoz** [comment]
Can you check that the environment variable JRE_HOME is set, and pointing to the correct location?

**Comment by tribouille** [comment]
Ok, it works with Oracle and OpenJDK...

Just got an error with OpenJDK when leaving the GUI (start and click cross to quit)
```
java.util.concurrent.ExecutionException: java.lang.InterruptedException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.jacpfx.rcp.worker.FXComponentInitWorker.done(FXComponentInitWorker.java:244)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:384)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:251)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2173)
        at org.jacpfx.rcp.util.WorkerUtil.invokeOnFXThreadAndWait(WorkerUtil.java:93)
        at org.jacpfx.rcp.worker.FXComponentInitWorker.executePostHandleAndAddComponent(FXComponentInitWorker.java:207)
        at org.jacpfx.rcp.worker.FXComponentInitWorker.call(FXComponentInitWorker.java:167)
        at org.jacpfx.rcp.worker.FXComponentInitWorker.call(FXComponentInitWorker.java:59)
        at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 3 more
```

Anyway, this issue can be closed, thanks.
