### ISSUE TITLE
DPFManager 3.0 IOException on "Check files" (Windows)

### ISSUE THREAD

**Issue by cweigel** [EasyinnovaSL/DPFManager#321]
Just installed the latest version 3.0 for Windows from the PREFORMA OpenSource portal (http://www.preforma-project.eu/downloads/DPFManager/Release-3.0/Windows/exec01-2016-10-28.zip) 

Seems that this is completely broken. I always get a IOException on Java when I normally start it as the User who also installed it:

![dpf3 0_crash_default_win7](https://cloud.githubusercontent.com/assets/13655319/20300591/2ba3c54e-ab20-11e6-845b-5b0135a5bad7.png)

    java.io.FileNotFoundException: C:\Program Files\DPF Manager\app\html\js\bootstrap.min.js (Zugriff verweigert)
    	at java.io.FileOutputStream.open0(Native Method)
    	at java.io.FileOutputStream.open(FileOutputStream.java:270)
    	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
    	at dpfmanager.shell.modules.report.core.ReportGenerator.copyHtmlFolder(ReportGenerator.java:519)
    	at dpfmanager.shell.modules.report.core.ReportGenerator.makeSummaryReport(ReportGenerator.java:655)
    	at dpfmanager.shell.modules.report.runnable.GlobalReportsRunnable.runTask(GlobalReportsRunnable.java:91)
    	at dpfmanager.shell.modules.threading.runnable.DpfRunnable.run(DpfRunnable.java:77)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)

When running "As Administrator" there is no Exception popping up but the check task seems to be in an endless loop. (waited > 2min for just a single TIFF file in Default)

**Comment by victormunoz** [comment]
Yes, it seems the windows installator has been corrupted. We have just rebuilt the installer. It can be downloaded from here: http://www.preforma-project.eu/downloads/DPFManager/Release-3.0/Windows/exec01-2016-10-28.zip
