### ISSUE TITLE
GUI Error (java.lang.NumberFormatException) after opening Reports tab in main GUI (OS X)

### ISSUE THREAD

**Issue by pieterdp** [EasyinnovaSL/DPFManager#327]
After completing a check of a folder with tiff-images, clicking on the "Reports" tab yields a `java.lang.NumberFormatException`.

The check was the default _Baseline HTML.dpf_ check of a folder. The generated HTML report is fine when opened in a web browser.

### Environment
* DPF version: 3.0
* Java version: 1.8.0_91
* OS: OS X 10.12.1

### Error message
```
Starting check: /Volumes/Storage/STORAGE_001/VIAA/map1_6/9c6rx94d3f
Generated report into '/Users/pieter/DPF Manager/reports/20161128/1/'
A gui error has occurred!
For input string: "html"
java.lang.NumberFormatException: For input string: "html"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at dpfmanager.shell.interfaces.gui.component.report.ReportsModel.readReports(ReportsModel.java:83)
	at dpfmanager.shell.interfaces.gui.component.report.ReportsModel.readIfNeed(ReportsModel.java:56)
	at dpfmanager.shell.interfaces.gui.component.report.ReportsView.handleMessageOnWorker(ReportsView.java:144)
	at dpfmanager.shell.core.adapter.DpfSimpleView.tractMessageOnWorker(DpfSimpleView.java:77)
	at dpfmanager.shell.core.adapter.DpfSimpleView.handle(DpfSimpleView.java:50)
	at dpfmanager.shell.core.adapter.DpfSimpleView.handle(DpfSimpleView.java:35)
	at org.jacpfx.rcp.util.WorkerUtil.prepareAndRunHandleMethod(WorkerUtil.java:225)
	at org.jacpfx.rcp.worker.EmbeddedFXComponentWorker.handleComponentExecution(EmbeddedFXComponentWorker.java:101)
	at org.jacpfx.rcp.worker.EmbeddedFXComponentWorker.run(EmbeddedFXComponentWorker.java:82)
```

**Comment by victormunoz** [comment]
Hello,
It seems the reports folder contains some folder with an unexpected name.
Can you check that the folder '/Users/pieter/DPF Manager/reports/20161128/1/' contains only folders named as numbers?
PS. Have you renamed any folder?

**Comment by pieterdp** [comment]
`/Users/pieter/DPF Manager/reports/20161128/1/` only contains the `html` folder and `report.html`. `/Users/pieter/DPF Manager/reports/20161128/` only contains folders named as numbers, but `/Users/pieter/DPF Manager/reports/` has plenty of folders (from older versions of the application) not named as numbers (but as filenames). Could that be the issue?

**Comment by victormunoz** [comment]
Yes, sure. These old reports are causing the issue. You should remove them...
We will fix this bug in the next release (at the end of this week).
Thank you for notifying this

**Comment by pieterdp** [comment]
@victormunoz removing the old folders indeed fixed the issue.
