### ISSUE TITLE
java.lang.NullPointerException with every file tested

### ISSUE THREAD

**Issue by kjadeglans** [EasyinnovaSL/DPFManager#332]
When testing multiple images in folder, every image produces a java error.

**Environment**

DPF Manager version 3.0
openjdk version "1.8.0_111"
OS: Ubuntu 16.04.1 LTS 64-bit

**Error message**

(error repeated for every file)

Conformance checker for file /buffertdisk/Preforma_test/161650/20161031_00001_0041.tif: [TiffConformanceChecker]
java.lang.NullPointerException
        at dpfmanager.conformancechecker.tiff.reporting.MetsReport.createNisoImageAssessmentMetadata(MetsReport.java:924)
        at dpfmanager.conformancechecker.tiff.reporting.MetsReport.constructTechMdWrap(MetsReport.java:1163)
        at dpfmanager.conformancechecker.tiff.reporting.MetsReport.buildReportIndividual(MetsReport.java:1435)
        at dpfmanager.conformancechecker.tiff.reporting.MetsReport.parseIndividual(MetsReport.java:1495)
        at dpfmanager.conformancechecker.tiff.TiffConformanceChecker.processFile(TiffConformanceChecker.java:607)
        at dpfmanager.shell.modules.conformancechecker.core.ProcessInput.processFile(ProcessInput.java:143)
        at dpfmanager.shell.modules.conformancechecker.runnable.ConformanceRunnable.runTask(ConformanceRunnable.java:76)
        at dpfmanager.shell.modules.threading.runnable.DpfRunnable.run(DpfRunnable.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by victormunoz** [comment]
It seems to be a problem when generating the METS report. However since it is an independent module this exception should not affect to the main process, and the other report formats should be generated. Are they?

Can you send us one of those files so that we can check what's wrong with the METS report?

**Comment by kjadeglans** [comment]
Yes, some reports are generated. 

i have:
1-20161017_00001_0001.tif.xml
report.html
summary.xml

Which files do you want me to send?

**Comment by victormunoz** [comment]
Just the tiff image, if possible

**Comment by kjadeglans** [comment]
The tif-files are ~45MB. How do i send one to you?

**Comment by victormunoz** [comment]
You can use wetransfer for example: https://wetransfer.com/

**Comment by kjadeglans** [comment]
file sent
