### ISSUE TITLE
another IOException

### ISSUE THREAD

**Issue by bert-packed** [EasyinnovaSL/DPFManager#349]
Hi, 

Started checking DPF Manager 3.0 on a Windows 10 machine with 8Mb RAM and JAVA8. 
Checking three tiff files of 136 Mb each.
received following error:

```
java.io.IOException: Het systeem kan het opgegeven pad niet vinden
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at dpfmanager.shell.modules.report.core.ReportGenerator.copyHtmlFolder(ReportGenerator.java:517)
	at dpfmanager.shell.modules.report.core.ReportGenerator.makeSummaryReport(ReportGenerator.java:655)
	at dpfmanager.shell.modules.report.runnable.GlobalReportsRunnable.runTask(GlobalReportsRunnable.java:91)
	at dpfmanager.shell.modules.threading.runnable.DpfRunnable.run(DpfRunnable.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

bert

**Comment by victormunoz** [comment]
Does this problem happen also if you check the files separately?

**Comment by bert-packed** [comment]
Hi Victor,
yes. just tested with one file and exactly the same error. 
bert

**Comment by victormunoz** [comment]
Are you getting this error with any file, or only with these three?
If you get the error always, then it could be a permissions problem.
Otherwise, could you send me one of these problematic tiffs?

**Comment by friesey** [comment]
Dear Folks,
I get the exact same error and it happens with any file. The files are from the google testsuite TIFF collection and usually work fine (with every other tool tested so far).
So for me it happens with any file.
Best, Yvonne

**Comment by victormunoz** [comment]
Although we have not been able to reproduce this problem, we have made some improvements on the software so that in the next release (at the end of this month), this problem will be either solved or a more explicit message of what's wrong will be shown.

**Comment by friesey** [comment]
Hi, thank you, I am looking forward to it! Best, Yvonne

Von: Victor Muñoz [mailto:notifications@github.com]
Gesendet: Donnerstag, 22. Dezember 2016 16:56
An: EasyinnovaSL/DPFManager
Cc: Tunnat Yvonne; Comment
Betreff: Re: [EasyinnovaSL/DPFManager] another IOException (#349)


Although we have not been able to reproduce this problem, we have made some improvements on the software so that in the next release (at the end of this month), this problem will be either solved or a more explicit message of what's wrong will be shown.
