### ISSUE TITLE
UI crashes when generating pdf report

### ISSUE THREAD

**Issue by cweigel** [EasyinnovaSL/DPFManager#37]
applies to installed version 1.2.1 (Windows 7)
processed folder (from the source distribution): [src_root]/src/test/resources/Block/Bad alignment Big E.tif

Config  file:
[config_04.dpf.txt](https://github.com/EasyinnovaSL/DPFManager/files/35571/config_04.dpf.txt)

error message:

    Processing file D:\workspace\preforma\DPFManager\src\test\resources\Block\Bad alignment Big E.tif
    Internal report 'reports/20151116/3/Bad alignment Big E.tif' created
    java.lang.NullPointerException
            at org.apache.pdfbox.pdmodel.common.PDStream.<init>(PDStream.java:131)
            at org.apache.pdfbox.pdmodel.graphics.xobject.PDJpeg.<init>(PDJpeg.java:104)
            at dpfmanager.shell.modules.reporting.ReportPDF.parseGlobal(ReportPDF.java:385)
            at dpfmanager.ReportGenerator.makeSummaryReport(ReportGenerator.java:723)
            at dpfmanager.shell.modules.classes.ProcessInput.ProcessFiles(ProcessInput.java:121)
            at dpfmanager.MainApp$4.call(MainApp.java:549)
            at dpfmanager.MainApp$4.call(MainApp.java:525)
            at javafx.concurrent.Task$TaskCallable.call(Unknown Source)
            at java.util.concurrent.FutureTask.run(Unknown Source)
            at java.lang.Thread.run(Unknown Source)
    Exception in thread "Thread-10" java.lang.IllegalArgumentException: The file: reports\20151116\3\report.pdf doesn't exist.
            at java.awt.Desktop.checkFileValidation(Unknown Source)
            at java.awt.Desktop.open(Unknown Source)
            at dpfmanager.MainApp$4$1.run(MainApp.java:562)
            at java.lang.Thread.run(Unknown Source)
    WARN  COSDocument - Warning: You did not close a PDF Document
    WARN  COSDocument - Warning: You did not close a PDF Document
    WARN  COSDocument - Warning: You did not close a PDF Document
    WARN  COSDocument - Warning: You did not close a PDF Document
    WARN  COSDocument - Warning: You did not close a PDF Document
    WARN  COSDocument - Warning: You did not close a PDF Document
    WARN  COSDocument - Warning: You did not close a PDF Document
    WARN  COSDocument - Warning: You did not close a PDF Document
    WARN  COSDocument - Warning: You did not close a PDF Document

**Comment by victormunoz** [comment]
Thank you for reporting this issue! I have been able to reproduce it.
Seems to be a bug when generating the report in PDF format with this concrete buggy image (images with filenames ending with "E" are erroneous).
I will take a look at and fix it. Thanks!
