### ISSUE TITLE
dpkg-Package requires missed library on Debian Jessie

### ISSUE THREAD

**Issue by art1pirat** [EasyinnovaSL/DPFManager#415]
Hi,

if you install the 3.2.1 on Debian Jessie, and start the GUI and validate a TIFF, you get following stacktrace pointing to a dependency which could not be resolved on Debian Jessie, because required library is not installable. As you can see the DPFManager requires the /usr/lib/x86_64-linux-gnu/libjpeg.so.8 with symbol  `LIBJPEG_8.0'. But Debian Jessie only provides libjpeg-turbo-6.2.

A workaround could be to package the required library in the dpkg.

Here the stacktrace:

Exception in thread "pool-2-thread-4" Exception in thread "pool-2-thread-7" Exception in thread "pool-2-thread-3" Exception in thread "pool-2-thread-2" java.lang.NoClassDefFoundError: Could not initialize class com.sun.imageio.plugins.jpeg.JPEGImageWriter
	at com.sun.imageio.plugins.jpeg.JPEGImageWriterSpi.createWriterInstance(JPEGImageWriterSpi.java:96)
	at javax.imageio.spi.ImageWriterSpi.createWriterInstance(ImageWriterSpi.java:351)
	at javax.imageio.ImageIO$ImageWriterIterator.next(ImageIO.java:843)
	at javax.imageio.ImageIO$ImageWriterIterator.next(ImageIO.java:827)
	at javax.imageio.ImageIO.getWriter(ImageIO.java:1596)
	at javax.imageio.ImageIO.write(ImageIO.java:1520)
	at dpfmanager.conformancechecker.tiff.reporting.HtmlReport.parseIndividual(HtmlReport.java:88)
	at dpfmanager.conformancechecker.tiff.TiffConformanceChecker.processFile(TiffConformanceChecker.java:445)
	at dpfmanager.shell.modules.conformancechecker.core.ProcessInput.processFile(ProcessInput.java:143)
	at dpfmanager.shell.modules.conformancechecker.runnable.ConformanceRunnable.runTask(ConformanceRunnable.java:84)
	at dpfmanager.shell.modules.threading.runnable.DpfRunnable.run(DpfRunnable.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.UnsatisfiedLinkError: /opt/DPFManager/runtime/lib/amd64/libjavajpeg.so: /usr/lib/x86_64-linux-gnu/libjpeg.so.8: version `LIBJPEG_8.0' not found (required by /opt/DPFManager/runtime/lib/amd64/libjavajpeg.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)

**Comment by victormunoz** [comment]
Thank you very much for reporting.
We will try to fix this for the next monthly release.

**Comment by victormunoz** [comment]
Finally we have decided to solve this problem by changing the thumbnails format to gif, which also works in debian jessie.
This is the related issue, that will be solved in the next release (at the end of this month): #453.
