### ISSUE TITLE
Error: summary.xml does not exist / Quick Check

### ISSUE THREAD

**Issue by MerleFri** [EasyinnovaSL/DPFManager#462]
Hello! When I run the DPF Manager, Version 3.4 (on Windows) with "Quick Check", the following error occurs on all tiff-files I tested:

java.io.FileNotFoundException: File 'C:\Users\FriM\DPF Manager\reports\20170721\4\summary.xml' does not exist
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:137)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1102)
	at dpfmanager.shell.modules.report.runnable.GlobalReportsRunnable.sendFtpCamel(GlobalReportsRunnable.java:130)
	at dpfmanager.shell.modules.report.runnable.GlobalReportsRunnable.runTask(GlobalReportsRunnable.java:110)
	at dpfmanager.shell.modules.threading.runnable.DpfRunnable.run(DpfRunnable.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

The error does not appear, when I choose "Full Check" option. When I run the DPF Manager Version 3.3 this error doesn't show up either. Is there anything I can do about that?

**Comment by victormunoz** [comment]
Hello! Thank you for contacting us!
Yes, we have realized that there is a bug when you have the "Send Feedback" option and you run a quick check.
We will correct this in the next release (at the end of this month).

By now, you can solve this by disabling the option "I authorize the DPF Manager to automatically send feedback" in the "About" section.

Thank you very much for your feedback!
