### ISSUE TITLE
[3.5.1] java.lang.ClassCastException: com.easyinnova.tiff.model.TagValue cannot be cast to com.easyinnova.tiff.model.types.Rational

### ISSUE THREAD

**Issue by thomasfischer-his** [EasyinnovaSL/DPFManager#473]
I tried to check [a TIFF file I got from a Wikipedia page](https://upload.wikimedia.org/wikipedia/az/9/9d/Suleyman_Cabbarov.tiff). Checking this file using DPFManager 3.5.1 on the command line gives reliably the following exception:
```
java.lang.ClassCastException: com.easyinnova.tiff.model.TagValue cannot be cast to com.easyinnova.tiff.model.types.Rational
        at dpfmanager.conformancechecker.tiff.reporting.MetsReport.createNisoGPSData(MetsReport.java:531)
        at dpfmanager.conformancechecker.tiff.reporting.MetsReport.createNisoImageCaptureMetadata(MetsReport.java:1064)
        at dpfmanager.conformancechecker.tiff.reporting.MetsReport.constructTechMdWrap(MetsReport.java:1450)
        at dpfmanager.conformancechecker.tiff.reporting.MetsReport.buildReportIndividual(MetsReport.java:1754)
        at dpfmanager.conformancechecker.tiff.reporting.MetsReport.parseIndividual(MetsReport.java:1814)
        at dpfmanager.shell.modules.report.core.ReportGenerator.writeIndividualReport(ReportGenerator.java:610)
        at dpfmanager.shell.modules.report.core.ReportGenerator.generateIndividualReport(ReportGenerator.java:567)
        at dpfmanager.shell.modules.report.runnable.IndividualReportsRunnable.runTask(IndividualReportsRunnable.java:62)
        at dpfmanager.shell.modules.conformancechecker.runnable.ConformanceRunnable.runTask(ConformanceRunnable.java:114)
        at dpfmanager.shell.modules.threading.runnable.DpfRunnable.run(DpfRunnable.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by victormunoz** [comment]
Thank you for reporting this!
We are going to fix this issue for the next release.
However, this error is not preventing the program to continue. You should obtain the reports anyway, (still a field in the METS report will be missing).

**Comment by thomasfischer-his** [comment]
> However, this error is not preventing the program to continue.
> You should obtain the reports anyway, (still a field in the METS report will be missing).

Yes, I saw that I was getting reports that looked fine, but was not sure if the results were still reliable given an exception occurred. Looking forward to see this bug fixed.

BTW, I found this TIFF file by simply searching for `filetype:tiff` in Google. This returns about a dozen of hits, mostly from Wikipedia/Wikimedia projects. I suggest adding those files to your benchmark collection.
