### ISSUE TITLE
build JFX Version fails to start with NullPtrException

### ISSUE THREAD

**Issue by cweigel** [EasyinnovaSL/DPFManager#48]
applies to commit:  3113e0601fa5eae1d8570c653eee9fdc9d6eff9e
System: Windows 7, Java(TM) SE Runtime Environment (build 1.8.0_66-b17)

It seems that it fails, if the default installation has been uninstalled and all DPFManager folders (users dir) have been removed. It also happens when the app folder is copied to a "blank" system:

    Exception in Application start method
    java.lang.reflect.InvocationTargetException
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            at java.lang.reflect.Method.invoke(Unknown Source)
            at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(Unknown Source)
            at com.sun.javafx.application.LauncherImpl.launchApplication(Unknown Source)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
            at java.lang.reflect.Method.invoke(Unknown Source)
            at sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
    Caused by: java.lang.RuntimeException: Exception in Application start method
            at com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
            at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(Unknown Source)
            at java.lang.Thread.run(Unknown Source)
    Caused by: java.lang.NullPointerException
            at dpfmanager.MainApp.ShowMain(MainApp.java:332)
            at dpfmanager.MainApp.LoadGui(MainApp.java:224)
            at dpfmanager.MainApp.start(MainApp.java:176)
            at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(Unknown Source)
            at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(Unknown Source)
            at com.sun.javafx.application.PlatformImpl.lambda$null$173(Unknown Source)
            at java.security.AccessController.doPrivileged(Native Method)
            at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(Unknown Source)
            at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
            at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
            at com.sun.glass.ui.win.WinApplication.lambda$null$148(Unknown Source)
            ... 1 more
    Exception running application dpfmanager.MainApp

**Comment by victormunoz** [comment]
Solved!
